services:
  pgrouting:
    image: pgrouting/pgrouting:16-3.4-3.6.1
    environment:
      POSTGRES_DB: pgrouting
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./Data/init.sql:/docker-entrypoint-initdb.d/init.sql
      
volumes:
  postgres_data: